spring:
  application:
    name: consumer
server:
  port: 9992
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:9990/eureka
    # 获取服务地址列表间隔时间，默认30秒
    registry-fetch-interval-seconds: 10